services:
  # --- DATABASE ---
  db:
    image: postgres:15-alpine
    container_name: signal-lab-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: signal_lab
    ports:
      - "5438:5432" # Выносим наружу на 5438, чтобы не мешать другим проектам
    networks:
      - app-network

  # --- BACKEND (NestJS) ---
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: signal-lab-api
    depends_on:
      - db
    ports:
      - "3001:3000" # API будет доступно на 3001
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/signal_lab"
      PORT: 3000
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    logging:
      driver: "json-file"
      options:
        tag: "nestjs-api"
    networks:
      - app-network

  # --- OBSERVABILITY: Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: signal-lab-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network

   # --- OBSERVABILITY: Loki (Logs) ---
  loki:
    image: grafana/loki:latest
    container_name: signal-lab-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network
  
  promtail:
    image: grafana/promtail:2.9.0
    container_name: signal-lab-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network

  # --- OBSERVABILITY: Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: signal-lab-grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - "3002:3000" # Grafana на 3002
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning

  networks:
    app-network:
      driver: bridge